### ISSUE TITLE
Unhandled error message when using "save as" on files outside the user directory

### ISSUE THREAD

**Issue by PaulchenPlump** [flathub/com.github.PintaProject.Pinta#34]
When I open an image outside my user directory and then choose "save as" I get the following error message:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Pinta.Actions.SaveDocumentImplmentationAction.SaveFileAs(Document document)
   at Pinta.Actions.SaveDocumentImplmentationAction.Activated(Object sender, DocumentCancelEventArgs e)
   at Pinta.Core.FileActions.RaiseSaveDocument(Document document, Boolean saveAs)
   at Pinta.Core.Document.Save(Boolean saveAs)
   at Pinta.Actions.SaveDocumentAsAction.Activated(Object sender, EventArgs e)
   at Pinta.Core.Command.<.ctor>b__33_0(Object o, ActivatedArgs args)
   at InvokeStub_ActivatedHandler.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)`

Problem seems to be the pre-selected path of the sandbox in the format "/run/user/<uid>/doc/<hex_id_number>". A simple "save" works though! Operating system is Debian 12 with flatpak in version 1.14.4 and pinta in 2.1.1!

Hope you can reproduce and fix it. Thanks in advance!

**Comment by cameronwhite** [comment]
I was able to reproduce by opening a file from `/tmp` and then doing Save As.
This probably requires a fix upstream in Pinta

**Comment by cameronwhite** [comment]
From https://bugs.launchpad.net/pinta/+bug/2045441, this seems like it may be solved with newer versions of the XDG portals library
